# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.freeholder.com:
    container_name: orderer.freeholder.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/freeholder.com/orderers/orderer.freeholder.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/freeholder.com/orderers/orderer.freeholder.com/tls/:/var/hyperledger/orderer/tls
    - orderer.freeholder.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.freeholder.com:
    container_name: peer0.org1.freeholder.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.freeholder.com
      - CORE_PEER_ADDRESS=peer0.org1.freeholder.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.freeholder.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.freeholder.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.freeholder.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.freeholder.com/peers/peer0.org1.freeholder.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.freeholder.com/peers/peer0.org1.freeholder.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.freeholder.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.org1.freeholder.com:
    container_name: peer1.org1.freeholder.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.freeholder.com
      - CORE_PEER_ADDRESS=peer1.org1.freeholder.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.freeholder.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.freeholder.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.freeholder.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.freeholder.com/peers/peer1.org1.freeholder.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.freeholder.com/peers/peer1.org1.freeholder.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.freeholder.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.org2.freeholder.com:
    container_name: peer0.org2.freeholder.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.freeholder.com
      - CORE_PEER_ADDRESS=peer0.org2.freeholder.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.freeholder.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.freeholder.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.freeholder.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.freeholder.com/peers/peer0.org2.freeholder.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.freeholder.com/peers/peer0.org2.freeholder.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.freeholder.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.org2.freeholder.com:
    container_name: peer1.org2.freeholder.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.freeholder.com
      - CORE_PEER_ADDRESS=peer1.org2.freeholder.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.freeholder.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.freeholder.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.freeholder.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.freeholder.com/peers/peer1.org2.freeholder.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.freeholder.com/peers/peer1.org2.freeholder.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.freeholder.com:/var/hyperledger/production
    ports:
      - 10051:10051
